spring:
  batch:
    initialize-schema: always
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/batch
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: create
